### ISSUE TITLE
Use URLTree to make a redirection inside a Guard

### ISSUE THREAD

**Issue by omarProgrammer** [malo22110/angular-ionic-unicorns#1]
Hello Malo,

It's better to return a `TreeUrl` to make a redirection instead of making a redirection directly with `nviagate`. You can find more details about that here https://juristr.com/blog/2018/11/better-route-guard-redirects/ 

BR,
Omar

https://github.com/malo22110/angular-ionic-unicorns/blob/0c19f3010bd78b1c448e79310acd358bff9e8281/src/app/core/guards/love-route.guard.ts#L25

**Comment by malo22110** [comment]
nice ! meci je vais fix ça ! :D

Le ven. 10 juin 2022 à 14:22, Omar BERRABEH ***@***.***> a
écrit :

**Comment by malo22110** [comment]
Fixed with TreeUrl
